import { cpSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";

const ysaEntry = Bun.resolveSync("@ysa-ai/ysa", import.meta.dir + "/..");
const ysaDir = resolve(dirname(ysaEntry), "..");
const containerSrc = resolve(ysaDir, "container");
const containerDst = resolve(import.meta.dir, "../src/container");

cpSync(containerSrc, containerDst, { recursive: true, force: true });

const files = [
  "sandbox-run.sh", "seccomp.json", "Containerfile",
  "Containerfile.proxy", "generate-ca.sh", "git-push-guard.sh", "git-safe-wrapper.sh",
  "container-sandbox-guard.sh", "claude-settings.json", "network-proxy.ts", "vibe-config.toml",
  "oci-network-hook.sh",
];

const imports = files.map((f, i) =>
  `import _asset${i} from "./container/${f}" with { type: "file" };`
).join("\n");

const entries = files.map((f, i) => `  "${f}": _asset${i}`).join(",\n");

writeFileSync(resolve(import.meta.dir, "../src/container-assets.ts"),
  `// Generated by scripts/prepare-container.ts — do not edit\n${imports}\nexport const assetPaths: Record<string, string> = {\n${entries},\n};\n`
);

console.log(`Container assets prepared from ${ysaDir}`);
